sudo: false
language: d
d:
  - dmd
  - dmd-2.075.0
  - ldc
branches:
  only:
  - master  
matrix:
  include:
    d: dmd-2.078.2
    env: [DEPLOY=1]
    # ddox dependencies (can be removed after 0.8.3 has been released)
    addons:
      apt:
        packages:
          - pkg-config
          - libevent-dev

install:
  - pyenv global system
  - pip3 install 'meson==0.47'
  - mkdir .ntmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o .ntmp/ninja-linux.zip
  - unzip .ntmp/ninja-linux.zip -d .ntmp

before_script:
  export PATH=$PATH:$PWD/.ntmp

script:
  # note: for dlang project tester, which doesn't clone automatically
  - meson build && ninja -j8 -C build
  - ninja -j8 -C build test -v
  - git submodule update --init --recursive
  #
  - cd test && ./run_tests.sh && cd ..
  - find test/coverage -type f -exec mv {} . \;
after_success:
 - bash <(curl -s https://codecov.io/bash)
